### ISSUE TITLE
Add Sigma rules support

### ISSUE THREAD

**Issue by araujof** [sysflow-telemetry/sysflow#101]
**Indicate project**
Processor

**Overview**
We want to enable Sigma rules evaluation in the SysFlow Processor, using our policy engine architecture as the base framework. 

**Tasks**
- [x] Refactoring to enable multi-language support
    - [x] Upgrade to Go 1.19
    - [x] Separation between policy front and backend compilation
    - [x] Generics (parametric record, to enable different backends for different input sources)
- [ ] Sigma frontend
    - [x] Conditions
    - [x] Search evaluation (event matching)
    - [x] Field modifiers
    - [ ] Field transformers
    - [ ] Keywords
    - [x] Field mapping support
- [x] Sigma backend support
- [ ] Field mapping for SysFlow
- [ ] Unit tests
- [ ] Sigma rule curation
- [ ] Performance tests
- [ ] Documentation

**Additional context**
Working branch: https://github.com/sysflow-telemetry/sf-processor/tree/go1.19-sigma

**Comment by araujof** [comment]
Release experimentally in 0.6.0
